-- Copyright (C) 2000-2013  Antonio Grandío Botella http://www.antoniograndio.com
-- Copyright (C) 2000-2013  Inmaculada Echarri San Adrián inma.echarri@gmail.com

-- This file is part of Catwin.

-- CatWin is free software; you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation; either version 2 of the License, or
-- at your option) any later version.

-- CatWin is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details:
-- http://www.gnu.org/copyleft/gpl.html

-- You should have received a copy of the GNU General Public License
-- along with Catwin Net; if not, write to the Free Software
-- Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

-- 
-- Estructura de tabla para la tabla `cuenplan`

CREATE TABLE `cuenplan` (
  `cuenta` int(3) NOT NULL,
  `nombre` varchar(255) NOT NULL,
  `subgrupo` int(2) NOT NULL,
  `descripcu` longtext NOT NULL
) ENGINE=MyISAM;

-- 
-- Volcar la base de datos para la tabla `cuenplan`
-- 

INSERT INTO `cuenplan` (`cuenta`, `nombre`, `subgrupo`, `descripcu`) VALUES 
(100, 'Capital social', 10, ''),
(101, 'Fondo social', 10, ''),
(102, 'Capital', 10, ''),
(103, 'Socios por desembolsos no exigidos...', 10, ''),
(104, 'Socios por aportaciones no dinerarias pendientes...', 10, ''),
(108, 'Acciones o participaciones propias en situaciones especiales', 10, ''),
(109, 'Acciones o participaciones propias para reducción de capital', 10, ''),
(110, 'Prima de emisión o asunción', 11, ''),
(111, 'Patrimonio neto por emisión de instrumentos financieros compuestos', 11, ''),
(112, 'Reserva legal', 11, ''),
(113, 'Reservas voluntarias', 11, ''),
(114, 'Reservas especiales', 11, ''),
(115, 'Reservas por pérdidas y ganancias actuariales y otros ajustes', 11, ''),
(118, 'Aportaciones de socios o propietarios', 11, ''),
(119, 'Diferencias por ajuste del capital a euros', 11, ''),
(120, 'Remanente', 12, ''),
(121, 'Resultados negativos de ejercicios anteriores', 12, ''),
(129, 'Resultados del ejercicio', 12, ''),
(130, 'Subvenciones oficiales de capital', 13, ''),
(131, 'Donaciones y legados de capital', 13, ''),
(135, 'Diferencias de conversión', 13, ''),
(132, 'Otras subvenciones, donaciones y legados', 13, ''),
(133, 'Ajustes por valoración en instrumentos financieros', 13, ''),
(134, 'Operaciones de cobertura', 13, ''),
(136, 'Ajustes por valoración en activos no corrientes y grupos enajenables de elementos mantenidos para la venta', 13, ''),
(137, 'Ingresos fiscales a distribuir en varios ejercicios', 13, ''),
(140, 'Provisión para retribuciones y otras prestaciones al personal.', 14, ''),
(141, 'Provisión para impuestos', 14, ''),
(142, 'Provisión para otras responsabilidades', 14, ''),
(143, 'Provisión por desmantelamiento, retiro o rehabilitación del inmovilizado.', 14, ''),
(145, 'Provisión para actuaciones medioambientales', 14, ''),
(146, 'Provisión para reestructuraciones', 14, ''),
(147, 'Provisiones por transacciones con pagos basados en instrumentos de patrimonio', 14, ''),
(150, 'Acciones o participaciones a largo plazo contabilizadas como pasivo', 15, ''),
(153, 'Desembolsos no exigidos por acciones o participaciones contabilizadas como pasivo.', 15, ''),
(154, 'Aportaciones no dinerarias pendientes por acciones o participaciones contabilizadas como pasivo', 15, ''),
(160, 'Deudas a largo plazo con entidades de crédito vinculadas', 16, ''),
(161, 'Proveedores de inmovilizado a largo plazo, partes vinculadas', 16, ''),
(162, 'Otras deudas a largo plazo con partes vinculadas', 16, ''),
(163, 'Otras deudas a largo plazo con partes vinculadas', 16, ''),
(170, 'Deudas a largo plazo con entidades de crédito', 17, ''),
(171, 'Deudas a largo plazo', 17, ''),
(172, 'Deudas a largo plazo transformables en subvenciones, donaciones y legados', 17, ''),
(173, 'Proveedores de inmovilizado a largo plazo', 17, ''),
(174, 'Acreedores por arrendamiento financiero a largo plazo', 17, ''),
(175, 'Efectos a pagar a largo plazo', 17, ''),
(176, 'Pasivos por derivados financieros a largo plazo', 17, ''),
(177, 'Obligaciones y bonos', 17, ''),
(178, 'Obligaciones y bonos convertibles', 17, ''),
(179, 'Deudas representadas en otros valores negociables', 17, ''),
(180, 'Fianzas recibidas a largo plazo', 18, ''),
(181, 'Anticipos recibidos por ventas o prestaciones de servicios a largo plazo', 18, ''),
(185, 'Depósitos recibidos a largo plazo', 18, ''),
(189, 'Garantías financieras a largo plazo', 18, ''),
(190, 'Acciones o participaciones emitidas', 19, ''),
(192, 'Suscriptores de acciones', 19, ''),
(194, 'Capital emitido pendiente de inscripción', 19, ''),
(195, 'Acciones o participaciones emitidas consideradas como pasivos financieros', 19, ''),
(197, 'Suscriptores de acciones consideradas coo pasivos financieros', 19, ''),
(199, 'Acciones o participaciones emitidas consideradas como pasivo financieros, pendientes de inscripción', 19, ''),
(200, 'Investigación', 20, ''),
(201, 'Desarrollo', 20, ''),
(202, 'Concesiones administrativas', 20, ''),
(203, 'Propiedad industrial', 20, ''),
(204, 'Fondo de comercio', 20, ''),
(205, 'Derechos de traspaso', 20, ''),
(206, 'Aplicaciones informáticas', 20, ''),
(209, 'Anticipos para inmovilizaciones intangibles', 20, ''),
(210, 'Terrenos y bienes naturales', 21, ''),
(211, 'Construcciones', 21, ''),
(212, 'Instalaciones técnicas', 21, ''),
(213, 'Maquinaria', 21, ''),
(214, 'Utillaje', 21, ''),
(215, 'Otras instalaciones', 21, ''),
(216, 'Mobiliario', 21, ''),
(217, 'Equipos para procesos de información', 21, ''),
(218, 'Elementos de transporte', 21, ''),
(219, 'Otro inmovilizado material', 21, ''),
(220, 'Inversiones en terrenos y bienes naturales', 22, ''),
(221, 'Inversiones en construcciones', 22, ''),
(230, 'Adaptación de terrenos y bienes naturales', 23, ''),
(231, 'Construcciones en curso', 23, ''),
(232, 'Instalaciones técnicas en montaje', 23, ''),
(233, 'Maquinaria en montaje', 23, ''),
(237, 'Equipos para procesos de información en montaje', 23, ''),
(239, 'Anticipos para inmovilizaciones materiales', 23, ''),
(240, 'Participaciones a largo plazo en partes vinculadas', 24, ''),
(241, 'Valores representativos de deuda a largo plazo de partes vinculadas', 24, ''),
(242, 'Créditos a largo plazo a partes vinculadas', 24, ''),
(249, 'Desembolsos pendientes sobre participaciones a largo plazo en partes vinculadas', 24, ''),
(250, 'Inversiones financieras a largo plazo en instrumentos de patrimonio', 25, ''),
(251, 'Valores representativos de deuda a largo plazo', 25, ''),
(252, 'Créditos a largo plazo', 25, ''),
(253, 'Créditos a largo plazo por enajenación de inmovilizado', 25, ''),
(254, 'Créditos a largo plazo al personal', 25, ''),
(255, 'Activos por derivados financieros a largo plazo', 25, ''),
(257, 'Activos por retribuciones a largo plazo de prestación definida', 25, ''),
(258, 'Imposiciones a largo plazo', 25, ''),
(259, 'Desembolsos pendientes sobre participaciones en el patrimonio neto a largo plazo', 25, ''),
(260, 'Fianzas constituidas a largo plazo', 26, ''),
(265, 'Depósitos constituidos a largo plazo', 26, ''),
(280, 'Amortización acumulada del inmovilizado intangible', 28, ''),
(281, 'Amortización acumulada del inmovilizado material', 28, ''),
(282, 'Amortización acumulada de las inversiones inmobiliarias', 28, ''),
(290, 'Deterioro de valor del inmovilizado intangible', 29, ''),
(291, 'Deterioro de valor del inmovilizado material', 29, ''),
(292, 'Deterioro de valor de las inversiones inmobiliarias', 29, ''),
(293, 'Deterioro de valor de participaciones a largo plazo en partes vinculadas', 29, ''),
(294, 'Deterioro de valor de valores representativos de deuda a largo plazo de partes vinculadas', 29, ''),
(295, 'Deterioro de valor de créditos a largo plazo a partes vinculadas', 29, ''),
(297, 'Deterioro de valor de valores representativos de deuda a largo plazo', 29, ''),
(298, 'Deterioro de valor de créditos a largo plazo', 29, ''),
(300, 'Mercaderías A', 30, ''),
(301, 'Mercaderías B', 30, ''),
(302, 'Mercaderías C', 30, ''),
(303, 'Mercaderías D', 30, ''),
(304, 'Mercaderías E', 30, ''),
(305, 'Mercaderías F', 30, ''),
(306, 'Mercaderías G', 30, ''),
(307, 'Mercaderías H', 30, ''),
(308, 'Mercaderías I', 30, ''),
(309, 'Mercaderías J', 30, ''),
(310, 'Materias primas A', 31, ''),
(312, 'Materias primas B', 31, ''),
(313, 'Materias primas C', 31, ''),
(314, 'Materias primas D', 31, ''),
(315, 'Materias primas E', 31, ''),
(316, 'Materias primas F', 31, ''),
(317, 'Materias primas H', 31, ''),
(318, 'Materias primas I', 31, ''),
(319, 'Materias primas J', 31, ''),
(320, 'Elementos y conjuntos incorporables', 32, ''),
(321, 'Combustibles', 32, ''),
(322, 'Repuestos', 32, ''),
(325, 'Materiales diversos', 32, ''),
(326, 'Embalajes', 32, ''),
(327, 'Envases', 32, ''),
(328, 'Material de oficina', 32, ''),
(330, 'Productos en curso A', 33, ''),
(331, 'Productos en curso B', 33, ''),
(332, 'Productos en curso C', 33, ''),
(333, 'Productos en curso D', 33, ''),
(334, 'Productos en curso E', 33, ''),
(335, 'Productos en curso F', 33, ''),
(336, 'Productos en curso G', 33, ''),
(337, 'Productos en curso H', 33, ''),
(338, 'Productos en curso I', 33, ''),
(339, 'Productos en curso J', 33, ''),
(340, 'Productos semiterminados A', 34, ''),
(341, 'Productos semiterminados B', 34, ''),
(342, 'Productos semiterminados C', 34, ''),
(343, 'Productos semiterminados D', 34, ''),
(344, 'Productos semiterminados E', 34, ''),
(345, 'Productos semiterminados F', 34, ''),
(346, 'Productos semiterminados G', 34, ''),
(347, 'Productos semiterminados H', 34, ''),
(348, 'Productos semiterminados I', 34, ''),
(349, 'Productos semiterminados J', 34, ''),
(350, 'Productos terminados A', 35, ''),
(351, 'Productos terminados B', 35, ''),
(352, 'Productos terminados C', 35, ''),
(353, 'Productos terminados D', 35, ''),
(354, 'Productos terminados E', 35, ''),
(355, 'Productos terminados F', 35, ''),
(356, 'Productos terminados G', 35, ''),
(357, 'Productos terminados H', 35, ''),
(358, 'Productos terminados I', 35, ''),
(359, 'Productos terminados J', 35, ''),
(360, 'Subproductos A', 36, ''),
(361, 'Subproductos B', 36, ''),
(365, 'Residuos A', 36, ''),
(366, 'Residuos B', 36, ''),
(368, 'Materiales recuperados A', 36, ''),
(369, 'Materiales recuperados B', 36, ''),
(390, 'Deterioro de valor de las mercaderias', 39, ''),
(391, 'Deterioro de valor de las materias primas', 39, ''),
(392, 'Deterioro de valor de otros aprovisionamientos', 39, ''),
(393, 'Deterioro de valor de los productos en curso', 39, ''),
(394, 'Deterioro de valor de los productos semiterminados', 39, ''),
(395, 'Deterioro de valor de los productos terminados', 39, ''),
(396, 'Deterioro de valor de los subproductos, residuos y materiales recuperados', 39, ''),
(400, 'Proveedores', 40, ''),
(401, 'Proveedores, efectos comerciales a pagar', 40, ''),
(403, 'Proveedores, empresas del grupo', 40, ''),
(404, 'Proveedores, empresas asociadas', 40, ''),
(405, 'Proveedores, otras partes vinculadas', 40, ''),
(406, 'Envases y embalajes a devolver a proveedores', 40, ''),
(407, 'Anticipos a proveedores', 40, ''),
(410, 'Acreedores por prestaciones de servicios', 41, ''),
(411, 'Acreedores, efectos comerciales a pagar', 41, ''),
(419, 'Acreedores por operaciones en común', 41, ''),
(430, 'Clientes', 43, ''),
(431, 'Clientes, efectos comerciales a cobrar', 43, ''),
(432, 'Clientes, operaciones de ''factoring''', 43, ''),
(433, 'Clientes, empresas del grupo', 43, ''),
(434, 'Clientes, empresas asociadas', 43, ''),
(435, 'Clientes, otras partes vinculadas', 43, ''),
(436, 'Clientes de dudoso cobro', 43, ''),
(437, 'Envases y embalajes a devolver por clientes', 43, ''),
(438, 'Anticipos de clientes', 43, ''),
(440, 'Deudores', 44, ''),
(441, 'Deudores, efectos comerciales a cobrar', 44, ''),
(446, 'Deudores de dudoso cobro', 44, ''),
(449, 'Deudores por operaciones en común', 44, ''),
(460, 'Anticipos de remuneraciones', 46, ''),
(465, 'Remuneraciones pendientes de pago', 46, ''),
(466, 'Remuneraciones mediante sistemas de aportación definida pendientes de pago', 46, ''),
(470, 'Hacienda Pública, deudora por IVA', 47, ''),
(471, 'Organismos de la Seguridad Social, deudores', 47, ''),
(472, 'Hacienda Pública, IVA soportado', 47, ''),
(473, 'Hacienda Pública, retenciones y pagos a cuenta', 47, ''),
(474, 'Activos por impuesto diferido', 47, ''),
(475, 'Hacienda Pública, acreedora por conceptos fiscales', 47, ''),
(476, 'Organismos de la Seguridad Social, acreedores', 47, ''),
(477, 'Hacienda Pública, IVA repercutido', 47, ''),
(479, 'Pasivos por diferencias temporarias imponibles', 47, ''),
(480, 'Gastos anticipados', 48, ''),
(485, 'Ingresos anticipados', 48, ''),
(490, 'Deterioro de valor de créditos por operaciones comerciales', 49, ''),
(493, 'Deterioro de valor de créditos por operaciones comerciales con partes vinculadas', 49, ''),
(499, 'Provisión para operaciones comerciales', 49, ''),
(500, 'Obligaciones y bonos a corto plazo', 50, ''),
(501, 'Obligaciones y bonos convertibles a corto plazo', 50, ''),
(502, 'Acciones o participaciones a corto plazo contabilizadas como pasivo', 50, ''),
(505, 'Deudas representadas en otros valores negociables a corto plazo', 50, ''),
(506, 'Intereses de empréstitos y otras emisiones análogas', 50, ''),
(507, 'Dividendos de emisiones contabilizadas como pasivo', 50, ''),
(509, 'Valores negociables amortizados', 50, ''),
(510, 'Deudas a corto plazo con entidades de crédito vinculadas', 51, ''),
(511, 'Proveedores de inmovilizado a corto plazo, partes vinculadas', 51, ''),
(512, 'Acreedores por arrendamiento financiero a corto plazo, partes vinculadas', 51, ''),
(513, 'Intereses a corto plazo de deudas con partes vinculadas', 51, ''),
(514, 'Dividendos de emisiones contabilizadas como pasivo con partes vinculadas', 51, ''),
(520, 'Deudas a corto plazo de entidades de crédito', 52, ''),
(521, 'Deudas a corto plazo', 52, ''),
(522, 'Deudas a corto plazo transformables en subvenciones, donaciones y legados', 52, ''),
(523, 'Proveedores de inmovilizado a corto plazo', 52, ''),
(524, 'Acreedores por arrendamiento financiero a corto plazo', 52, ''),
(525, 'Efectos a pagar a corto plazo', 52, ''),
(526, 'Dividendo activo a pagar', 52, ''),
(527, 'Intereses a corto plazo de deudas con entidades de crédito', 52, ''),
(528, 'Intereses a corto plazo de deudas', 52, ''),
(529, 'Provisiones a corto plazo', 52, ''),
(530, 'Participaciones a corto plazo en partes vinculadas', 53, ''),
(531, 'Valores representativos de deuda a corto plazo de partes vinculadas', 53, ''),
(532, 'Créditos a corto plazo a partes vinculadas', 53, ''),
(533, 'Intereses a corto plazo de valores representativos de deuda de partes vinculadas', 53, ''),
(534, 'Intereses a corto plazo de créditos a partes vinculas', 53, ''),
(535, 'Dividendo a cobrar de inversiones financieras en partes vinculadas', 53, ''),
(539, 'Desembolsos pendientes sobre participaciones a corto plazo de partes vinculadas', 53, ''),
(540, 'Inversiones financieras temporales en instrumentos de patrimonio', 54, ''),
(541, 'Valores representativos de deuda a corto plazo', 54, ''),
(542, 'Créditos a corto plazo', 54, ''),
(543, 'Créditos a corto plazo por enajenación de inmovilizado', 54, ''),
(544, 'Créditos a corto plazo al personal', 54, ''),
(545, 'Dividendo a cobrar', 54, ''),
(546, 'Intereses a corto plazo de inversiones financieras', 54, ''),
(547, 'Intereses a corto plazo de créditos', 54, ''),
(548, 'Imposiciones a corto plazo', 54, ''),
(549, 'Desembolsos pendientes sobre instrumentos de patrimonio a corto plazo', 54, ''),
(550, 'Titular de la explotación', 55, ''),
(551, 'Cuenta corriente con socios y administradores', 55, ''),
(552, 'Cuenta corriente con otras personas y entidades vinculadas', 55, ''),
(553, 'Cuentas corrientes en fusiones y escisiones', 55, ''),
(554, 'Cuenta corriente con uniones temporales de empresas y comunidades de bienes', 55, ''),
(555, 'Partidas pendientes de aplicación', 55, ''),
(556, 'Desembolsos exigidos sobre participaciones en el patrimonio neto', 55, ''),
(557, 'Dividendo activo a cuenta', 55, ''),
(558, 'Socios por desembolsos exigidos', 55, ''),
(559, 'Derivados financieros a corto plazo', 55, ''),
(560, 'Fianzas recibidas a corto plazo', 56, ''),
(561, 'Depósitos recibidos a corto plazo', 56, ''),
(565, 'Fianzas constituidas a corto plazo', 56, ''),
(566, 'Depósitos constituidos a corto plazo', 56, ''),
(567, 'Intereses pagados por anticipado', 56, ''),
(568, 'Intereses cobrados por anticipado', 56, ''),
(569, 'Garantías financieras a corto plazo', 56, ''),
(570, 'Caja, euros', 57, ''),
(571, 'Caja, moneda extranjera', 57, ''),
(572, 'Bancos e instituciones de crédito c/c vista, euros', 57, ''),
(573, 'Bancos e instituciones de crédito c/c vista, moneda extranjera', 57, ''),
(574, 'Bancos e instituciones de crédito, cuentas de ahorro, euros', 57, ''),
(575, 'Bancos e instituciones de crédito, cuentas de ahorro, moneda extranjera', 57, ''),
(576, 'Inversiones a corto plazo de gran liquidez', 57, ''),
(580, 'Inmovilizado', 58, ''),
(581, 'Inversiones con personas y entidades vinculadas', 58, ''),
(582, 'Inversiones financieras', 58, ''),
(583, 'Existencias, deudores comerciales y otras cuentas a cobrar', 58, ''),
(584, 'Otros activos', 58, ''),
(585, 'Provisiones', 58, ''),
(586, 'Deudoas con características especiales', 58, ''),
(587, 'Deudas con personas y entidades vinculadas', 58, ''),
(588, 'Acreedores comerciales y otras cuentas a pagar', 58, ''),
(589, 'Otros pasivos', 58, ''),
(593, 'Deterioro de valor de participaciones a corto plazo en partes vinculadas', 59, ''),
(594, 'Deterioro del valor de valores representativos de deuda a corto plazo de partes vinculadas', 59, ''),
(595, 'Deterioro del valor de créditos a corto plazo a partes vinculadas', 59, ''),
(597, 'Deterioro de valor de valores representativos de deuda a corto plazo', 59, ''),
(598, 'Deterioro de valor de créditos a corto plazo', 59, ''),
(599, 'Deterioro de valor de activos no corrientes mantenidos para la venta', 59, ''),
(600, 'Compras de mercaderías', 60, ''),
(601, 'Compras de materias primas', 60, ''),
(602, 'Compras de otros aprovisionamientos', 60, ''),
(606, 'Descuentos sobre compras por pronto pago', 60, ''),
(607, 'Trabajos realizados por otras empresas', 60, ''),
(608, 'Devoluciones de compras y operaciones similares', 60, ''),
(609, '''Rappels'' por compras', 60, ''),
(610, 'Variación de existencias de mercaderías', 61, ''),
(611, 'Variación de existencias de materias primas', 61, ''),
(612, 'Variación de existencias de otros aprovisionamientos', 61, ''),
(620, 'Gastos en investigación y desarrollo del ejercicio', 62, ''),
(621, 'Arrendamientos y cánones', 62, ''),
(622, 'Reparaciones y conservación', 62, ''),
(623, 'Servicios de profesionales independientes', 62, ''),
(624, 'Transportes', 62, ''),
(625, 'Primas de seguros', 62, ''),
(626, 'Servicios bancarios y similares', 62, ''),
(627, 'Publicidad, propaganda y relaciones públicas', 62, ''),
(628, 'Suministros', 62, ''),
(629, 'Otros servicios', 62, ''),
(630, 'Impuesto sobre beneficios', 63, ''),
(631, 'Otros tributos', 63, ''),
(633, 'Ajustes negativos en la imposición sobre beneficios', 63, ''),
(634, 'Ajustes negativos en la imposición indirecta', 63, ''),
(636, 'Devolución de impuestos', 63, ''),
(638, 'Ajustes positivos en la imposición sobre beneficios', 63, ''),
(639, 'Ajustes positivos en la imposición indirecta', 63, ''),
(640, 'Sueldos y salarios', 64, ''),
(641, 'Indemnizaciones', 64, ''),
(642, 'Seguridad Social a cargo de la empresa', 64, ''),
(643, 'Retribuciones a largo plazo mediante sistemas de aportación definida', 64, ''),
(644, 'Retribuciones a largo plazo mediante sistemas de prestación definida', 64, ''),
(645, 'Retribuciones al personal mediante instrumentos de patrimonio', 64, ''),
(649, 'Otros gastos sociales', 64, ''),
(650, 'Pérdidas de créditos comerciales incobrables', 65, ''),
(651, 'Resultados de operaciones en común', 65, ''),
(659, 'Otras pérdidas en gestión corriente', 65, ''),
(660, 'Gastos financieros por actualización de provisiones', 66, ''),
(661, 'Intereses de obligaciones y bonos', 66, ''),
(662, 'Intereses de deudas', 66, ''),
(663, 'Pérdidas por valoración de instrumentos financieros por su valor razonable', 66, ''),
(664, 'Dividendos de acciones o participaciones contabilizadas como pasivo', 66, ''),
(665, 'Intereses por descuento de efectos', 66, ''),
(666, 'Pérdidas en participaciones y valores representativos de deuda', 66, ''),
(667, 'Pérdidas de créditos', 66, ''),
(668, 'Diferencias negativas de cambio', 66, ''),
(669, 'Otros gastos financieros', 66, ''),
(670, 'Pérdidas procedentes del inmovilizado intangible', 67, ''),
(671, 'Pérdidas procedentes del inmovilizado material', 67, ''),
(672, 'Pérdidas procedentes de las inversiones inmobiliarias', 67, ''),
(673, 'Pérdidas procedentes de participaciones a largo plazo en partes vinculadas', 67, ''),
(675, 'Pérdidas por operaciones con obligaciones propias', 67, ''),
(678, 'Gastos excepcionales', 67, ''),
(680, 'Amortización del inmovilizado intangible', 68, ''),
(681, 'Amortización del inmovilizado material', 68, ''),
(682, 'Amortización de las inversiones inmoviliarias', 68, ''),
(690, 'Pérdidas por deterioro del inmovilizado intangible', 69, ''),
(691, 'Pérdidas por deterioro del inmovilizado material', 69, ''),
(692, 'Pérdidas por deterioro de las inversiones inmobiliarias', 69, ''),
(693, 'Pérdidas por deterioro de existencias', 69, ''),
(694, 'Pérdidas por deterioro de créditos comerciales', 69, ''),
(695, 'Dotación a la provisión por operaciones comerciales', 69, ''),
(696, 'Pérdidas por deterioro de participaciones y valores representativos de deuda a largo plazo', 69, ''),
(697, 'Pérdidas por deterioro de créditos a largo plazo', 69, ''),
(698, 'Pérdidas por deterioro de participaciones y valores representativos de deuda a corto plazo', 69, ''),
(699, 'Pérdidas por deterioro de créditos a corto plazo', 69, ''),
(700, 'Ventas de mercaderías', 70, ''),
(701, 'Ventras de productos terminados', 70, ''),
(702, 'Ventras de productos semiterminados', 70, ''),
(703, 'Ventas de subproductos y residuos', 70, ''),
(704, 'Ventas de envases y embalajes', 70, ''),
(705, 'Prestaciones de servicios', 70, ''),
(706, 'Descuentos sobre ventas por pronto pago', 70, ''),
(708, 'Devoluciones de ventas y operaciones similares', 70, ''),
(709, '''Rappels'' sobre ventas', 70, ''),
(710, 'Variación de existencias de productos en curso', 71, ''),
(711, 'Variación de existencias de productos semiterminados', 71, ''),
(712, 'Variación de existencias de productos terminados', 71, ''),
(713, 'Variaciónde existencias de subproductos, residuos y materiales recuperados', 71, ''),
(730, 'Trabajos realizados para el inmovilizado intangible', 73, ''),
(731, 'Trabajos realizados para el inmovilizado material', 73, ''),
(732, 'Trabajos realizados en inversiones inmobiliarias', 73, ''),
(733, 'Trabajos realizados para el inmovilizado en curso', 73, ''),
(740, 'Subvenciones, donaciones y legados a la explotación', 74, ''),
(746, 'Subvenciones, donaciones y legados de capital transferidos al resultado del ejercicio', 74, ''),
(747, 'Otras subvenciones, donaciones y legados transferidos al resultado del ejercicio.', 74, ''),
(751, 'Resultados de operaciones en común', 75, ''),
(752, 'Ingresos por arrendamientos', 75, ''),
(753, 'Ingresos de propiedad industrial cedida en explotación', 75, ''),
(754, 'Ingresos por comisiones', 75, ''),
(755, 'Ingresos por servicios al personal', 75, ''),
(759, 'Ingresos por servicios diversos', 75, ''),
(760, 'Ingresos de participaciones en instrumentos de patrimonio', 76, ''),
(761, 'Ingresos de valores representativos de deuda', 76, ''),
(762, 'Ingresos de créditos', 76, ''),
(763, 'Beneficios por valoración de instrumentos financieros por su valor razonable', 76, ''),
(766, 'Beneficios en participaciones y valores representativos de deuda', 76, ''),
(767, 'Ingresos de activos afectos y de derechos de reembolso relativos a retribuciones a largo plazo', 76, ''),
(768, 'Diferencias positivas de cambio', 76, ''),
(769, 'Otros ingresos financieros', 76, ''),
(770, 'Beneficios procedentes del inmovilizado intangible', 77, ''),
(771, 'Beneficios procedentes del inmovilizado material', 77, ''),
(772, 'Beneficios procedentes de las inversiones inmobiliarias', 77, ''),
(773, 'Beneficios procedentes de participaciones...', 77, ''),
(774, 'Diferencia negativa en combinaciones de negocios', 77, ''),
(775, 'Beneficios por operaciones con obligaciones propias', 77, ''),
(778, 'Ingresos excepcionales', 77, ''),
(790, 'Reversión del deterioro del inmovilizado intangible', 79, ''),
(791, 'Reversión del deterioro del inmovilizado material', 79, ''),
(792, 'Reversión del deterioro de las inversiones inmobiliarias', 79, ''),
(793, 'Reversión del deterioro de existencias', 79, ''),
(794, 'Reversión del deterioro de créditos comerciales', 79, ''),
(795, 'Exceso de provisiones', 79, ''),
(796, 'Reversión del deterioro de participaciones y valores representativos de deuda a largo plazo', 79, ''),
(797, 'Reversión del deterioro de créditos a largo plazo', 79, ''),
(798, 'Reversión del deterioro de participaciones y valores representativos de deuda a corto plazo', 79, ''),
(799, 'Reversión del deterioro de créditos a corto plazo', 79, ''),
(800, 'Pérdidas en activos financieros disponibles para la venta', 80, ''),
(802, 'Transferencia de beneficios en activos financieros disponibles para la venta', 80, ''),
(810, 'Pérdidas por coberturas de flujos de efectivo', 81, ''),
(811, 'Pérdidas por coberturas de inversiones netas en el extranjero', 81, ''),
(812, 'Transferencia de beneficios por coberturas de flujos de efectivo', 81, ''),
(813, 'Transferencia de beneficios por coberturas de inversiones netas en un negocio en el extranjero', 81, ''),
(820, 'Diferencias de conversión negativas', 82, ''),
(821, 'Transferencia de diferencias de conversión positivas', 82, ''),
(830, 'Impuestos sobre beneficios', 83, ''),
(833, 'Ajustes negativos en la imposición sobre beneficios', 83, ''),
(834, 'Ingresos fiscales por diferencias permanentes', 83, ''),
(835, 'Ingresos fiscales por deducciones y bonificaciones', 83, ''),
(836, 'Transferencia de diferencias permanentes', 83, ''),
(837, 'Transferencia de deducciones y bonificaciones', 83, ''),
(838, 'Ajustes positivos en la imposición sobre beneficios', 83, ''),
(840, 'Transferencia de subvenciones oficiales de capital', 84, ''),
(841, 'Transferencias de donaciones y legados de capital', 84, ''),
(842, 'Transferencia de otras subvenciones, donaciones y legados', 84, ''),
(850, 'Pérdidas actuariales', 85, ''),
(851, 'Ajustes negativos en activos por retribuciones a largo plazo de prestación definida', 85, ''),
(860, 'Pérdidas en activos no corrientes y grupos enajenables de elementos mantenidos para la venta', 86, ''),
(862, 'Transferencia de beneficios en activos no corrientes y grupos enajenables de elementos para la venta', 86, ''),
(891, 'Deterioro de participaciones en el patrimonio, empresas del grupo', 89, ''),
(892, 'Deterioro de participaciones en el patrimonio, empresas asocidas', 89, ''),
(900, 'Beneficios en activos financieros disponibles para la venta', 90, ''),
(902, 'Transferencia de pérdidas de activos financieros disponibles para la venta', 90, ''),
(910, 'Beneficios por coberturas de flujos de efectivo', 91, ''),
(911, 'Beneficios por coberturas de una inversión neta en un negocio en el extranjero', 91, ''),
(912, 'Transferencia de pérdidas por coberturas de flujos de efectivo', 91, ''),
(913, 'Transferencia de pérdidas por coberturas de una inversión neta en un negocio en el extranjero', 91, ''),
(920, 'Diferencias de conversión positivas', 92, ''),
(921, 'Transferencia de diferencias de conversión negativas', 92, ''),
(940, 'Ingresos de subvenciones oficiales de capital', 94, ''),
(941, 'Ingresos de donaciones y legados de capital', 94, ''),
(942, 'Ingresos de otras subvenciones, donaciones y legados', 94, ''),
(950, 'Ganancias actuariales', 95, ''),
(951, 'Ajustes positivos en activos por retribuciones a largo plazo de prestación definida', 95, ''),
(960, 'Beneficios en activos no corrientes y grupos enajenables de elementos mantenidos para la venta', 96, ''),
(962, 'Transferencia de pérdidas en activos no corrientes y grupos enajenables de elementos mantenidos para la venta', 96, ''),
(991, 'Recuperación de ajustes valorativos negativos previos, empresas del grupo', 99, ''),
(992, 'Recuperación de ajustes valorativos negativos previos, empresas asociadas', 99, ''),
(993, 'Transferencia por deterioro de ajustes valorativos negativos previos, empresas del grupo', 99, ''),
(994, 'Transferencia por deterioro de ajustes valorativos negativos previos, empresas asociadas', 99, '');
