-- Copyright (C) 2000-2013  Antonio Grandío Botella http://www.antoniograndio.com
-- Copyright (C) 2000-2013  Inmaculada Echarri San Adrián inma.echarri@gmail.com

-- This file is part of Catwin.

-- CatWin is free software; you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation; either version 2 of the License, or
-- at your option) any later version.

-- CatWin is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details:
-- http://www.gnu.org/copyleft/gpl.html

-- You should have received a copy of the GNU General Public License
-- along with Catwin Net; if not, write to the Free Software
-- Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

-- Estructura de tabla para la tabla `subcplan`

CREATE TABLE `subcplan` (
  `subcuenta` int(6) NOT NULL,
  `nombre` varchar(255) NOT NULL,
  `cuenta` int(3) NOT NULL,
  `descripsu` longtext NOT NULL
) ENGINE=MyISAM;

-- 
-- Volcar la base de datos para la tabla `subcplan`
-- 

INSERT INTO `subcplan` (`subcuenta`, `nombre`, `cuenta`, `descripsu`) VALUES 
(1030, 'Socios por desembolsos no exigidos, capital social', 103, ''),
(1034, 'Socios por desembolsos no exigidos, capital pendiente de inscripción', 103, ''),
(1040, 'Socios por aportaciones no dinerarias pendientes, capital social', 104, ''),
(1044, 'Socios por aportaciones no dinerarias pendientes, capital pendiente de inscripción.', 104, ''),
(1110, 'Patrimonio neto por emisión de instrumentos financieros compuestos', 111, ''),
(1111, 'Resto de instrumentos de patrimonio neto', 111, ''),
(1140, 'Reservas para acciones o participaciones de la sociedad dominante', 114, ''),
(1141, 'Reservas estatutarias', 114, ''),
(1142, 'Reserva por capital amortizado', 114, ''),
(1143, 'Reserva por fondo de comercio', 114, ''),
(1144, 'Reservas por acciones propias aceptadas en garantía', 114, ''),
(1340, 'Cobertura de flujos de efectivo', 134, ''),
(1341, 'Cobertura de una inversión neta en un negocio en el extranjero', 134, ''),
(1370, 'Ingresos fiscales por diferencias permanentes a distribuir en varios ejercicios', 137, ''),
(1371, 'Ingresos fiscales por deducciones y bonificaciones a distribuir en varios ejercicios', 137, ''),
(1533, 'Desembolsos no exigidos, empresas del grupo', 153, ''),
(1534, 'Desembolsos no exigidos, empresas asociadas', 153, ''),
(1535, 'Desembolsos no exigidos, otras partes vinculadas', 153, ''),
(1536, 'Otros desembolsos no exigidos', 153, ''),
(1543, 'Aportaciones no dinerarias pendientes, empresas del grupo', 154, ''),
(1544, 'Aportaciones no dinerarias pendientes, empresas asociadas', 154, ''),
(1545, 'Aportaciones no dinerarias pendientes, otras partes vinculadas', 154, ''),
(1546, 'Otras aportaciones no dinerarias pendientes', 154, ''),
(1603, 'Deudas a largo plazo con entidades de crédito, empresas del grupo', 160, ''),
(1604, 'Deudas a largo plazo con entidades de crédito, empresas asociadas', 160, ''),
(1605, 'Deudas a largo plazo con otras entidades de crédito vinculadas', 160, ''),
(1613, 'Proveedores de inmovilizado a largo plazo, empresas del grupo', 161, ''),
(1614, 'Proveedores de inmovilizado a largo plazo, empresas asociadas', 161, ''),
(1615, 'Proveedores de inmovilizado a largo plazo, otras partes vinculadas', 161, ''),
(1623, 'Acreedores por arrendamiento financiero a largo plazo, empresas de grupo', 162, ''),
(1624, 'Acreedores por arrendamiento financiero a largo plazo, empresas asociadas', 162, ''),
(1625, 'Acreedores por arrendamiento financiero a largo plazo, otras partes vinculadas', 162, ''),
(1633, 'Otras deudas a largo plazo, empresas del grupo', 163, ''),
(1634, 'Otras deudas a largo plazo, empresas asociadas', 163, ''),
(1635, 'Otras deudas a largo plazo, con otras partes vinculadas', 163, ''),
(1765, 'Pasivos por derivados financieros a largo plazo, cartera de negociación', 176, ''),
(1768, 'Pasivos por derivados financieros a largo plazo, instrumentos de cobertura', 176, ''),
(2403, 'Participaciones a largo plazo en empresas del grupo', 240, ''),
(2404, 'Participaciones a largo plazo en empresas asociadas', 240, ''),
(2405, 'Participaciones a largo plazo en otras partes vinculadas', 240, ''),
(2413, 'Valores representativos de deuda a largo plazo de empresas de grupo', 241, ''),
(2414, 'Valores representativos de deuda a largo plazo de empresas asociadas', 241, ''),
(2415, 'Valores representativos de deuda a largo plazo de otras partes vinculadas', 241, ''),
(2423, 'Créditos a largo plazo a empresas del grupo', 242, ''),
(2424, 'Créditos a largo plazo a empresas asociadas', 242, ''),
(2425, 'Crédtios a largo plazo a otras partes vinculadas', 242, ''),
(2493, 'Desembolsos pendientes sobre participaciones a largo plazo en empresas del grupo', 249, ''),
(2494, 'Desembolsos pendientes sobre participaciones a largo plazo en empresas asociadas', 249, ''),
(2495, 'Desembolsos pendientes sobre participaciones a largo plazo en otras partes vinculadas', 249, ''),
(2550, 'Activos por derivados financieros a largo plazo, cartera de negociación', 255, ''),
(2553, 'Activos por derivados financieros a largo plazo, instrumentos de cobertura', 255, ''),
(2800, 'Amortización acumulada de investigación', 280, ''),
(2801, 'Amortización acumulada de desarrollo', 280, ''),
(2802, 'Amortización acumulada de concesiones administrativas', 280, ''),
(2803, 'Amortización acumulada de propiedad industrial', 280, ''),
(2805, 'Amortización acumulada de derechos de traspaso', 280, ''),
(2806, 'Amortización acumulada de aplicaciones informáticas', 280, ''),
(2811, 'Amortización acumulada de construcciones', 281, ''),
(2812, 'Amortización acumulada de instalaciones técnicas', 281, ''),
(2813, 'Amortización acumulada de maquinaria', 281, ''),
(2814, 'Amortización acumulada de utillaje', 281, ''),
(2815, 'Amortización acumulada de otras instalaciones', 281, ''),
(2816, 'Amortización acumulada de mobiliario', 281, ''),
(2817, 'Amortización acumulada de equipos para procesos de información', 281, ''),
(2818, 'Amortización acumulada de elementos de transporte', 281, ''),
(2819, 'Amortización acumulada de otro inmovilizado material', 281, ''),
(2900, 'Deterioro de valor de investigación', 290, ''),
(2901, 'Deterioro de valor de desarrollo', 290, ''),
(2902, 'Deterioro de valor de concesiones administrativas', 290, ''),
(2903, 'Deterioro de valor de propiedad industrial', 290, ''),
(2905, 'Deterioro de valor de derechos de traspaso', 290, ''),
(2906, 'Deterioro de valor de aplicaciones informáticas', 290, ''),
(2910, 'Deterioro de valor de terrenos y bienes naturales', 291, ''),
(2911, 'Deterioro de valor de construcciones', 291, ''),
(2912, 'Deterioro de valor de instalaciones técnicas', 291, ''),
(2913, 'Deterioro de valor de maquinaria', 291, ''),
(2914, 'Deterioro de valor de utillaje', 291, ''),
(2915, 'Deterioro de valor de otras instalaciones', 291, ''),
(2916, 'Deterioro de valor de mobiliario', 291, ''),
(2917, 'Deterioro de valor de equipos para procesos de información', 291, ''),
(2918, 'Deterioro de valor de elementos de transporte', 291, ''),
(2919, 'Deterioro de valor de otro inmovilizado material', 291, ''),
(2920, 'Deterioro de valor de los terrenos y bienes naturales', 292, ''),
(2921, 'Deterioro de valor de construcciones', 292, ''),
(2933, 'Deterioro de valor de participaciones a largo plazo en empresas del grupo', 293, ''),
(2934, 'Deterioro de valor de participaciones a largo plazo en empresas asociadas', 293, ''),
(2943, 'Deterioro de valor de valores representativos de deuda a largo plazo de empresas del grupo', 294, ''),
(2944, 'Deterioro de valor de valores representativos de deuda a largo plazo ede empresas vinculadas', 294, ''),
(2945, 'Deterioro de valor de valores representativos de deuda a largo plazo a de otras partes vinculadas', 294, ''),
(2953, 'Deterioro de valor de créditos a largo plazo de empresas del grupo', 295, ''),
(2954, 'Deterioro de valor de créditos a largo plazo a empresas vinculadas', 295, ''),
(2955, 'Deterioro de valor de créditos a largo plazo a otras partes vinculadas', 295, ''),
(4000, 'Proveedores (euros)', 400, ''),
(4004, 'Proveedores (moneda extranjera)', 400, ''),
(4009, 'Proveedores, facturas pendientes de recibir o de formalizar', 400, ''),
(4030, 'Proveedores, empresas del grupo (euros)', 403, ''),
(4031, 'Efectos comerciales a pagar, empresas del grupo', 403, ''),
(4034, 'Proveedores, empresas del grupo (moneda extranjera)', 403, ''),
(4036, 'Envases y embalajes a devolver a proveedores, empresas del grupo', 403, ''),
(4039, 'Proveedores, empresas del grupo, facturas pendientes de recibir o de formalizar', 403, ''),
(4100, 'Acreedores por prestaciones de servicios (euros)', 410, ''),
(4104, 'Acreedores por prestaciones de servicios (moneda extranjera)', 410, ''),
(4109, 'Acreedores por prestaciones de servicios, facturas pendientes de recibir o de formalizar', 410, ''),
(4300, 'Clientes (euros)', 430, ''),
(4304, 'Clientes (moneda extranjera)', 430, ''),
(4309, 'Clientes, facturas pendientes de formalizar', 430, ''),
(4310, 'Efectos comerciales e cartera', 431, ''),
(4311, 'Efectos comerciales descontados', 431, ''),
(4312, 'Efectos comerciales en gestion de cobro', 431, ''),
(4315, 'Efectos comerciales impagados', 431, ''),
(4330, 'Clientes empresas del grupo (euros)', 433, ''),
(4331, 'Efectos comerciales a cobrar, empresas del grupo', 433, ''),
(4332, 'Clientes empresas del grupo, operaciones de ''factoring''', 433, ''),
(4334, 'Clientes empresas del grupo (moneda extranjera)', 433, ''),
(4336, 'Clientes empresas del grupo de dudoso cobro', 433, ''),
(4337, 'Envases y embalajes a devolvder a clientes, empresas del grupo', 433, ''),
(4339, 'Clientes empresas del grupo, facturas pendientes de formalizar', 433, ''),
(4400, 'Deudores (euros)', 440, ''),
(4404, 'Deudores (moneda extranjera)', 440, ''),
(4409, 'Deudores, facturas pendientes de formalizar', 440, ''),
(4410, 'Deudores, efectos comerciales en cartera', 441, ''),
(4411, 'Deudores, efectos comerciales descontados', 441, ''),
(4412, 'Deudores, efectos comerciaes en gestión de cobro', 441, ''),
(4415, 'Deudores, efectos comerciales impagados', 441, ''),
(4700, 'Hacienda Pública, deudora por IVA', 470, ''),
(4708, 'Hacienda Pública, deudora por subvenciones concedidas', 470, ''),
(4709, 'Hacienda Pública, deudora por devolución de impuestos', 470, ''),
(4720, 'Hacienda Pública, IVA soportado', 472, ''),
(4730, 'Hacienda Pública, retenciones y pagos a cuenta', 473, ''),
(4740, 'Activos por diferencias temporarias deducibles', 474, ''),
(4742, 'Derechos por deducciones y bonificaciones pendientes de aplicar', 474, ''),
(4745, 'Crédito por pérdidas a compensar del ejercicio', 474, ''),
(4750, 'Hacienda Pública, acreedora por IVA', 475, ''),
(4751, 'Hacienda Pública, acreedora por retenciones practicadas', 475, ''),
(4752, 'Hacienda Pública, acreedora por impuesto sobre sociedades', 475, ''),
(4758, 'Hacienda Pública, acreedora por subvenciones a reintegrar', 475, ''),
(4933, 'Deterioro de valor de créditos por operaciones comerciales con empresas del grupo', 493, ''),
(4934, 'Deterioro de valor de créditos por operaciones comerciales con empresas vinculadas', 493, ''),
(4935, 'Deterioro de valor de crédtios por operaciones comerciales con otras partes vinculadas', 493, ''),
(4994, 'Provisión para contratos onerosos.', 499, ''),
(4999, 'Provisión para otras operaciones comerciales', 499, ''),
(5090, 'Obligaciones y bonos amortizados', 509, ''),
(5091, 'Obligaciones y bonos convertibles amortizados', 509, ''),
(5095, 'Otros valores negociables amortizados', 509, ''),
(5103, 'Deudas a corto plazo con entidades de crédito, empresas del grupo', 510, ''),
(5104, 'Deudas a corto plazo con entidades de crédito, empresas asociadas', 510, ''),
(5105, 'Deudas a corto plazo con otras entidades de crédito vinculadas', 510, ''),
(5113, 'Proveedores de inmovilizado a corto plazo, empresas del grupo', 511, ''),
(5114, 'Proveedores de inmovilizado a corto plazo, empresas asociadas', 511, ''),
(5115, 'Proveedores de inmovilizado a corto plazo, otras partes vinculadas', 511, ''),
(5123, 'Acreedores por arrendamiento financiero a corto plazo, empresas del grupo', 512, ''),
(5124, 'Acreedores por arrendamiento financiero a corto plazo, empresas asociadas', 512, ''),
(5125, 'Acreedores por arrendamiento financiero a corto plazo, otras partes vinculadas', 512, ''),
(5133, 'Otras deudas a corto plazo con empresas de grupo', 513, ''),
(5134, 'Otras deudas a corto plazo de deudas, empresas asociadas', 513, ''),
(5135, 'Otras deudas a corto plazo con otras partes vinculadas', 513, ''),
(5143, 'Intereses a corto plazo de deudas, empresas del grupo', 514, ''),
(5144, 'Intereses a corto plazo de deudas, empresas asociadas', 514, ''),
(5145, 'Intereses a corto plazo de deudas, otras partes vinculadas', 514, ''),
(5200, 'Préstamos a corto plazo de entidades de crédito', 520, ''),
(5201, 'Deudas a corto plazo por crédito dispuesto', 520, ''),
(5208, 'Deudas por efectos descontados', 520, ''),
(5209, 'Deudas por operaciones de ''factoring''', 520, ''),
(5290, 'Provisión a corto plazo por retribuciones al personal', 529, ''),
(5291, 'Provisión a corto plazo para impuestos', 529, ''),
(5292, 'Provisión a corto plazo para otras responsabilidades', 529, ''),
(5293, 'Provisión a corto plazo por desmantelamiento, retiro o rehabilitación del inmovilizado', 529, ''),
(5295, 'Provisión a corto plazo para actuaciones medioambientales', 529, ''),
(5296, 'Provisión a corto plazo para reestructuraciones', 529, ''),
(5297, 'Provisión a corto plazo por transacciones con pagos basados en instrumentos de patrimonio', 529, ''),
(5303, 'Participaciones a corto plazo, en empresas del grupo', 530, ''),
(5304, 'Participaciones a corto plazo, en empresas asociadas', 530, ''),
(5305, 'Participaciones a corto plazo, en otras partes vinculadas', 530, ''),
(5313, 'Valores representativos de deuda a corto plazo de empresas del grupo', 531, ''),
(5314, 'Valores representativos de deuda a corto plazo de empresas asociadas', 531, ''),
(5315, 'Valores representativos de deuda a corto plazo de otras partes vinculadas', 531, ''),
(5323, 'Créditos a corto plazo a empresas del grupo', 532, ''),
(5324, 'Créditos a corto plazo a empresas asociadas', 532, ''),
(5325, 'Créditos a corto plazo a otras partes vinculadas', 532, ''),
(5333, 'Intereses a corto plazo de valores representativos de deuda de empresas del grupo', 533, ''),
(5334, 'Intereses a corto plazo de valores representativos de deuda de empresas asociadas', 533, ''),
(5335, 'Intereses a corto plazo de valores representativos de deuda de otras partes vinculadas', 533, ''),
(5343, 'Intereses a corto plazo de créditos a empresas del grupo', 534, ''),
(5344, 'Intereses a corto plazo de créditos a empresas vinculadas', 534, ''),
(5345, 'Intereses a corto plazo de créditos a otras partes vinculads', 534, ''),
(5353, 'Dividendo a cobrar de empresas del grupo', 535, ''),
(5354, 'Dividendo a cobrar de empresas asociadas', 535, ''),
(5355, 'Dividendo a cobrar de otras partes vinculadas', 535, ''),
(5393, 'Desembolsos pendientes sobre participaciones a corto plazo en empresas del grupo', 539, ''),
(5394, 'Desembolsos pendientes sobre participaciones a corto plazo en empresas asociadas', 539, ''),
(5395, 'Desembolsos pendientes sobre participaciones a corto plazo en otras partes vinculadas', 539, ''),
(5523, 'Cuenta corriente con empresas del grupo', 552, ''),
(5524, 'Cuenta corriente con empresas asociadas', 552, ''),
(5525, 'Cuenta corriente con otras partes vinculadas', 552, ''),
(5530, 'Socios de sociedad disuelta', 553, ''),
(5531, 'Socios, cuenta de fusión', 553, ''),
(5532, 'Socios de sociedad escindida', 553, ''),
(5533, 'Socios, cuenta de escisión', 553, ''),
(5563, 'Desembolsos exigidos sobre participaciones, empresas del grupo', 556, ''),
(5564, 'Desembolsos exigidos sobre participaciones, empresas asociadas', 556, ''),
(5565, 'Desembolsos exigidos sobre participaciones, otras partes vinculadas', 556, ''),
(5566, 'Desembolsos exigidos sobre participaciones de otras empresas', 556, ''),
(5580, 'Socios por desembolsos exigidos sobre acciones o participaciones ordinarias', 558, ''),
(5585, 'Socios por desembolsos, exigidos sobre acciones o participaciones consideradas como pasivos financieros', 558, ''),
(5590, 'Activos por derivados financieros a corto plazo', 559, ''),
(5593, 'Activos por derivados financieros a corto plazo, instrumentos de cobertura', 559, ''),
(5595, 'Pasivos por derivados financieros a corto plazo, cartera de negociación', 559, ''),
(5598, 'Pasivos por derivados financieros a corto plazo, instrumentos de cobertura', 559, ''),
(5933, 'Deterioro de valor de participaciones a corto plazo en empresas del grupo', 593, ''),
(5934, 'Deterioro de valor de participaciones a corto plazo en empresas asociadas', 593, ''),
(5943, 'Deterioro de valor de valores representativos de deuda a corto plazo de empresas del grupo', 594, ''),
(5944, 'Deterioro de valor de valores representativos de deuda a corto plazo de empresas asociadas', 594, ''),
(5945, 'Deterioro de valor de valores representativos de deuda a corto plazo de otras partes vinculadas', 594, ''),
(5953, 'Deterioro del valor de créditos a corto plazo a empresas del grupo', 595, ''),
(5954, 'Deterioro del valor de créditos a corto plazo a empresas asociadas', 595, ''),
(5955, 'Deterioro del valor de créditos a corto plazo a otras partes vinculadas', 595, ''),
(5990, 'Deterioro de valor de inmovilizado no corriente mantenido a la venta', 599, ''),
(5991, 'Deterioro de valor de inversiones con personas y entidades vinculadas no corrientes mantenidas para la venta', 599, ''),
(5992, 'Deterioro de valor de inversiones financieras no corrientes mantenidas para la venta', 599, ''),
(5993, 'Deterioro de valor de existencias, deudores comerciales y otras cuentas a cobrar integrados en un grupo enajenable mantenido para la venta', 599, ''),
(5994, 'Deterioro de valor de otros activos mantenidos para la venta', 599, ''),
(6060, 'Descuentos sobre compras por pronto pago de mercaderías', 606, ''),
(6061, 'Descuentos sobre compras por pronto pago de materias primas', 606, ''),
(6062, 'Descuentos sobre compras por pronto pago de otros aprovisionamientos', 606, ''),
(6080, 'Devoluciones por compras de mercaderías', 608, ''),
(6081, 'Devoluciones por compras de materias primas', 608, ''),
(6082, 'Devoluciones por compras de otros aprovisionamientos', 608, ''),
(6090, '''Rappels'' por compras de mercaderías', 609, ''),
(6091, '''Rappels'' por compras de materias primas', 609, ''),
(6092, '''Rappels'' por compras de otros apovisionamientos', 609, ''),
(6300, 'Impuesto corriente', 630, ''),
(6301, 'Impuesto diferido', 630, ''),
(6341, 'Ajustes negativos en IVA de activo corriente', 634, ''),
(6342, 'Ajustes negativos en IVA de inversiones', 634, ''),
(6391, 'Ajustes positivos en IVA de activo corriente', 639, ''),
(6392, 'Ajustes positivos en IVA de inversiones', 639, ''),
(6440, 'Contribuciones anuales', 644, ''),
(6442, 'Otros costes', 644, ''),
(6450, 'Retribuciones al personal liquidados con instrumentos de patrimonio', 645, ''),
(6457, 'Retribuciones al personal liquidados en efectivo basado en instrumentos de patrimonio', 645, ''),
(6510, 'Beneficio transferido (gestor)', 651, ''),
(6511, 'Pérdida soportada (partícipe o asociado no gestor)', 651, ''),
(6610, 'Intereses por obligaciones y bonos largo plazo, empresas del grupo', 661, ''),
(6611, 'Intereses por obligaciones y bonos largo plazo, empresas asociadas', 661, ''),
(6612, 'Intereses por obligaciones y bonos largo plazo, otras partes vinculadas', 661, ''),
(6613, 'Intereses por obligaciones y bonos largo plazo, otras empresas', 661, ''),
(6615, 'Intereses por obligaciones y bonos corto plazo, empresas del grupo', 661, ''),
(6616, 'Intereses por obligaciones y bonos corto plazo, empresas asociadas', 661, ''),
(6617, 'Intereses por obligaciones y bonos corto plazo, otras partes vinculadas', 661, ''),
(6618, 'Intereses por obligaciones y bonos corto plazo, otras empresas', 661, ''),
(6620, 'Intereses de deudas, empresas del grupo', 662, ''),
(6621, 'Intereses de deudas, empresas asociadas', 662, ''),
(6622, 'Intereses de deudas, otras partes vinculadas', 662, ''),
(6623, 'Intereses de deudas con entidades de crédito', 662, ''),
(6624, 'Intereses de deudas, otras empresas', 662, ''),
(6630, 'Pérdidas de cartera de negociación', 663, ''),
(6631, 'Pérdidas de designados por la empresa', 663, ''),
(6632, 'Pérdidas de disponibles para la venta', 663, ''),
(6633, 'Pérdidas de instrumentos de cobertura', 663, ''),
(6640, 'Dividendos de pasivos, empresas de grupo', 664, ''),
(6641, 'Dividendos de pasivos, empresas asociadas', 664, ''),
(6642, 'Didivendos de pasivos, otras partes vinculadas', 664, ''),
(6643, 'Dividendos de pasivos, otras empresas', 664, ''),
(6650, 'Intereses por descuento de efectos a entidades de crédito del grupo', 665, ''),
(6651, 'Intereses por descuento de efectos a entidades de crédito asociadas', 665, ''),
(6652, 'Intereses por descuento de efectos a entidades de crédito vinculadas', 665, ''),
(6653, 'Intereses por descuento de efectos a otras entidades de crédito', 665, ''),
(6654, 'Intereses por operaciones de ''factoring'' con entidades de crédito del grupo', 665, ''),
(6655, 'Intereses por operaciones de ''factoring'' con entidades de crédito asociadas', 665, ''),
(6656, 'Intereses por operaciones de ''factoring'' con entidades de crédito vinculadas', 665, ''),
(6657, 'Intereses por operaciones de ''factoring'' con otras entidades de crédito', 665, ''),
(6660, 'Pérdidas en valores representativos de deuda a largo plazo, empresas del grupo', 666, ''),
(6661, 'Pérdidas en valores representativos de deuda a largo plazo, empresas asociadas', 666, ''),
(6662, 'Pérdidas en valores representativos de deuda a largo plazo, otras partes vinculadas', 666, ''),
(6663, 'Pérdidas en participaciones y valores representativos de deuda a largo plazo, otras empresas', 666, ''),
(6665, 'Pérdidas en participaciones y valores representativos de deuda a corto plazo, empresas del grupo', 666, ''),
(6666, 'Pérdidas en participaciones y valores representativos de deuda a corto plazo, empresas asociadas', 666, ''),
(6667, 'Pérdidas en valores representativos de deuda a corto plazo, otras partes vinculadas', 666, ''),
(6668, 'Pérdidas en valores representativos de deuda a corto plazo, otras empresas', 666, ''),
(6670, 'Pérdidas de créditos a largo plazo, empresas del grupo', 667, ''),
(6671, 'Pérdidas de créditos a largo plazo, empresas asociadas', 667, ''),
(6672, 'Pérdidas de créditos a largo plazo, otras partes vinculadas', 667, ''),
(6673, '', 667, ''),
(6675, 'Pérdidas de créditos a corto plazo, empresas del grupo', 667, ''),
(6676, 'Pérdidas de créditos a corto plazo, empresas asociadas', 667, ''),
(6677, 'Pérdidas de créditos a corto plazo, otras partes vinculadas', 667, ''),
(6678, 'Pérdidas de créditos a corto plazo, otras empresas', 667, ''),
(6733, 'Pérdidas procedentes de participaciones a largo plazo, empresas del grupo', 673, ''),
(6734, 'Pérdidas procedentes de participaciones a largo plazo, empresas asociadas', 673, ''),
(6735, 'Pérdidas procedentes de participaciones a largo plazo, otras partes vinculadas', 673, ''),
(6930, 'Pérdidas por deterioro de productos terminados y en curso de fabricación', 693, ''),
(6931, 'Pérdidas por deterioro de mercaderías', 693, ''),
(6932, 'Pérdidas por deterioro de materias primas', 693, ''),
(6933, 'Pérdidas por deterioro de otros aprovisionamientos', 693, ''),
(6954, 'Dotación a la provisión por contratos onerosos', 695, ''),
(6959, 'Dotación a la provisión para otras operaciones comerciales', 695, ''),
(6960, 'Pérdidas por deterioro de participaciones en instrumentos de patrimonio neto a largo plazo, empresas del grupo', 696, ''),
(6961, 'Pérdidas por deterioro de participaciones en instrumentos de patrimonio neto a largo plazo, empresas asociadas', 696, ''),
(6962, 'Pérdidas por deterioro de participaciones en instrumentos de patrimonio neto a largo plazo, otras partes vinculadas', 696, ''),
(6963, 'Pérdidas por deterioro de participaciones en instrumentos de patrimonio neto a largo plazo, otras empresas', 696, ''),
(6965, 'Pérdidas por deterioro en valores representativos de deuda a largo plazo, empresas del grupo', 696, ''),
(6966, 'Pérdidas por deterioro en valores representativos de deuda a largo plazo, empresas asociadas', 696, ''),
(6967, 'Pérdidas por deterioro en valores representativos de deuda a largo plazo, otras partes vinculadas', 696, ''),
(6968, 'Pérdidas por deterioro en valores representativos de deuda a largo plazo, otras empresas', 696, ''),
(6970, 'Pérdidas por deterioro de créditos a largo plazo, empresas del grupo', 697, ''),
(6971, 'Pérdidas por deterioro de créditos a largo plazo, empresas asociadas', 697, ''),
(6972, 'Pérdidas por deterioro de créditos a largo plazo, otras partes vinculadas', 697, ''),
(6973, 'Pérdidas por deterioro de créditos a largo plazo, otras empresas', 697, ''),
(6980, 'Pérdidas por deterioro de participaciones en instrumentos de patrimonio neto a corto plazo, empresas del grupo', 698, ''),
(6981, 'Pérdidas por deterioro de participaciones en instrumentos de patrimonio neto a corto plazo,, empresas asociadas', 698, ''),
(6985, 'Pérdidas por deterioro en valores representativos de deuda a corto plazo, empresas del grupo', 698, ''),
(6986, 'Pérdidas por deterioro en valores representativos de deuda a corto plazo, empresas asociadas', 698, ''),
(6987, 'Pérdidas por deterioro en valores representativos de deuda a corto plazo, otras partes vinculadas', 698, ''),
(6988, 'Pérdidas por deterioro en valores representativos de deuda a corto plazo, de otras empresas', 698, ''),
(6990, 'Pérdidas por deterioro de créditos a corto plazo, empresas del grupo', 699, ''),
(6991, 'Pérdidas por deterioro de créditos a corto plazo, empresas asociadas', 699, ''),
(6992, 'Pérdidas por deterioro de créditos a corto plazo, otras partes vinculadas', 699, ''),
(6993, 'Pérdidas por deterioro de créditos a corto plazo, otras empresas', 699, ''),
(7060, 'Descuentos sobre ventas por pronto pago de mercaderías', 706, ''),
(7061, 'Descuentos sobre ventas por pronto pago de productos terminados', 706, ''),
(7062, 'Descuentos sobre ventas por pronto pago de productos semiterminados', 706, ''),
(7063, 'Descuentos sobre ventas por pronto pago de subproductos y residuos', 706, ''),
(7080, 'Devoluciones de ventas de mercaderías', 708, ''),
(7081, 'Devoluciones de ventas de productos terminados', 708, ''),
(7082, 'Devoluciones de ventas de productos semiterminados', 708, ''),
(7083, 'Devoluciones de ventas de subproductos y residuos', 708, ''),
(7084, 'Devoluciones de ventas de envases y embalajes', 708, ''),
(7090, '''Rappels'' sobre ventas de mercaderías', 709, ''),
(7091, '''Rappels'' sobre ventas de productos terminados', 709, ''),
(7092, '''Rappels'' sobre ventas de productos semiterminados', 709, ''),
(7093, '''Rappels'' sobre ventas de subproductos y residuos', 709, ''),
(7094, '''Rappels'' sobre ventas de envases y embalajes', 709, ''),
(7510, 'Pérdida transferida (gestor)', 751, ''),
(7511, 'Beneficio atribuido (partícipe o asociado no gestor)', 751, ''),
(7600, 'Ingresos de participaciones en instrumentos de patrimonio, empresas del grupo', 760, ''),
(7601, 'Ingresos de participaciones en instrumentos de patrimonio, empresas asociadas', 760, ''),
(7602, 'Ingresos de participaciones en instrumentos de patrimonio, otras partes vinculadas', 760, ''),
(7603, 'Ingresos de participaciones en instrumentos de patrimonio, otras empresas', 760, ''),
(7610, 'Ingresos de valores representatios de deuda, empresas del grupo', 761, ''),
(7611, 'Ingresos de valores representatios de deuda, empresas asociadas', 761, ''),
(7612, 'Ingresos de valores representatios de deuda, otras partes vinculadas', 761, ''),
(7613, 'Ingresos de valores representatios de deuda, otras empresas', 761, ''),
(7620, 'Ingresos de créditos a largo plazo', 762, ''),
(76200, 'Ingresos de créditos a largo plazo, empresas del grupo', 762, ''),
(76201, 'Ingresos de créditos a largo plazo, empresas asociadas', 762, ''),
(76202, 'Ingresos de créditos a largo plazo, otras partes vinculadas', 762, ''),
(76203, 'Ingresos de créditos a largo plazo, otras empresas', 762, ''),
(7621, 'Ingresos de créditos a corto plazo', 762, ''),
(76210, 'Ingresos de créditos a corto plazo, empresas del grupo', 762, ''),
(76211, 'Ingresos de créditos a corto plazo, empresas asociadas', 762, ''),
(76212, 'Ingresos de créditos a corto plazo, otras partes vinculadas', 762, ''),
(76213, 'Ingresos de créditos a corto plazo, otras empresas', 762, ''),
(7630, 'Beneficios de cartera de negociación', 763, ''),
(7631, 'Beneficios de designados por la empresa', 763, ''),
(7632, 'Beneficios de disponibles para la venta', 763, ''),
(7633, 'Beneficios de instrumentos de cobertura', 763, ''),
(7660, 'Beneficios en valores representativos de deuda a largo plazo, empresas del grupo', 766, ''),
(7661, 'Beneficios en valores representativos de deuda a largo plazo, empresas asociadas', 766, ''),
(7662, 'Beneficios en valores representativos de deuda a largo plazo, otras partes vinculadas', 766, ''),
(7663, 'Beneficios en participaciones y valores representativos de deuda a largo plazo, otras empresas', 766, ''),
(7665, 'Beneficios en participaciones y valores representativos de deuda a corto plazo, empresas del grupo', 766, ''),
(7666, 'Beneficios en participaciones y valores representativos de deuda a corto plazo, empresas vinculadas', 766, ''),
(7667, 'Beneficios en valores representativos de deuda a corto plazo, otras partes vinculadas', 766, ''),
(7668, 'Beneficios en valores representativos de deuda a corto plazo, otras empresas', 766, ''),
(7733, 'Beneficios procedentes de participaciones a largo plazo, empresas del grupo', 773, ''),
(7734, 'Beneficios procedentes de participaciones a largo plazo, empresas asociadas', 773, ''),
(7735, 'Beneficios procedentes de participaciones a largo plazo, otras partes vinculadas', 773, ''),
(7930, 'Reversión del deterioro de productos terminados y en curso de fabricación', 793, ''),
(7931, 'Reversión del deterioro de mercaderías', 793, ''),
(7932, 'Reversión del deterioro de materias primas', 793, ''),
(7933, 'Reversión del deterioro de otros aprovisionamientos', 793, ''),
(7950, 'Exceso de provisión por retribuciones al personal', 795, ''),
(7951, 'Exceso de provisión para impuestos', 795, ''),
(7952, 'Exceso de provisión para otras responsabilidades', 795, ''),
(7954, 'Exceso de provisión por operaciones comerciales', 795, ''),
(79544, 'Exceso de provisión por contratos onerosos', 795, ''),
(79549, 'Exceso de rovisión para otras operaciones comerciales', 795, ''),
(7955, 'Exceso de provisión para actuaciones mediambientales', 795, ''),
(7956, 'Exceso de provisión para reestructuraciones', 795, ''),
(7957, 'Exceso de provisión por transacciones con pagos basados en instrumentos de patrimonio', 795, ''),
(7960, 'Reversión del deterioro de participaciones en instrumentos de patrimonio neto a largo plazo, empresas del grupo', 796, ''),
(7961, 'Reversión del deterioro de participaciones en instrumentos de patrimonio neto a largo plazo, empresas asociadas', 796, ''),
(7965, 'Reversión del deterioro de valores representativos de deuda a largo plazo, empresas del grupo', 796, ''),
(7966, 'Reversión del deterioro de valores representativos de deuda a largo plazo, empresas asociadas', 796, ''),
(7967, 'Reversión del deterioro de valores representativos de deuda a largo plazo, otras partes vinculadas', 796, ''),
(7968, 'Reversión del deterioro de valores representativos de deuda a largo plazo, otras empresas', 796, ''),
(7970, 'Reversión del deterioro de créditos a largo plazo, empresas del grupo', 797, ''),
(7971, 'Reversión del deterioro de créditos a largo plazo, empresas asociadas', 797, ''),
(7972, 'Reversión del deterioro de créditos a largo plazo, otras partes vinculadas', 797, ''),
(7973, 'Reversión del deterioro de créditos a largo plazo, otras empresas', 797, ''),
(7980, 'Reversión del deterioro de participaciones en instrumentos de patrimonio neto a corto plazo, empresas del grupo', 798, ''),
(7981, 'Reversión del deterioro de participaciones en instrumentos de patrimonio neto a corto plazo, empresas asociadas', 798, ''),
(7985, 'Reversión del deterioro en valores representativos de deuda a corto plazo, empresas del gupo', 798, ''),
(7986, 'Reversión del deterioro en valores representativos de deuda a corto plazo, empresas asociadas', 798, ''),
(7987, 'Reversión del deterioro en valores representativos de deuda a corto plazo, otras partes vinculadas', 798, ''),
(7988, 'Reversión del deterioro en valores representativos de deuda a corto plazo, otras empresas', 798, ''),
(7990, 'Reversión del deterioro de créditos a corto plazo, empresas del grupo', 799, ''),
(7991, 'Reversión del deterioro de créditos a corto plazo, empresas asociadas', 799, ''),
(7992, 'Reversión del deterioro de créditos a corto plazo, otras partes vinculadas', 799, ''),
(7993, 'Reversión del deterioro de créditos a corto plazo, otras empresas', 799, ''),
(8300, 'Impuesto corriente', 830, ''),
(8301, 'Impuesto diferido', 830, '');
